version: 1.0.{build}

environment:
  matrix:
    - TARGET: x86_64-pc-windows-msvc

install:
  - appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain stable
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustup -V
  - cargo -V

clone_depth: 1

skip_tags: true

build: false

test_script:
  - cargo test --all
  - cargo test --examples
